### ISSUE TITLE
TypeError: Cannot assign to read only property 'navigator' of object '#<Window>'

### ISSUE THREAD

**Issue by CaiqueR** [alephjs/aleph.js#177] opened 2021-03-06 16:37 UTC
When a I run `aleph dev` I get this error:

![image](https://user-images.githubusercontent.com/42003129/110213962-2285b100-7e81-11eb-9da6-745d8fa08377.png)

**Comment by shadowtime2000** [comment] 2021-03-06 18:34
Duplicate of #169. It has already been fixed on master, so will be fixed in next release.

**Closed by shadowtime2000** 2021-03-06 18:34 UTC
