### ISSUE TITLE
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)

### ISSUE THREAD

**Issue by Bestulo** [alephjs/aleph.js#83] opened 2021-01-11 20:26 UTC
I followed instructions on the [get-started](https://alephjs.org/docs/get-started) page step by step. I didn't do anything extra. I open index and have this: 

![image](https://user-images.githubusercontent.com/23301025/104234146-5b794a80-5429-11eb-8d8c-cb9e706da28e.png)

Specs:
Deno version 1.6.2
VSCode version 1.52.1
Deno extension version 2.3.3

`.vscode` directory was created properly by Aleph's `init` script, and `settings.json` does contain `"deno.enable": true`

**Comment by shadowtime2000** [comment] 2021-01-11 20:37
@Bestulo Hover over the imports and have the Deno language server fetch and cache the modules. It needs to do that to detect React's types I think.

**Comment by Bestulo** [comment] 2021-01-11 20:54
I `aleph dev`, which installed a big bunch of dependencies. However, even though it installed many things from `cdn-esm-sh`, which can be seen below, it's still highlighted as before and reads `Cannot find module 'https://esm.sh/react' or its corresponding type declarations.ts(2307)`

![image](https://user-images.githubusercontent.com/23301025/104236861-8ebdd880-542d-11eb-9413-461ecc0089a4.png)

Additionally, the same problem as described above persists.

![image](https://user-images.githubusercontent.com/23301025/104236915-a6955c80-542d-11eb-9668-140995a9ea9f.png)

![image](https://user-images.githubusercontent.com/23301025/104236935-abf2a700-542d-11eb-89f6-8ef43a7ebc92.png)

**Comment by Soremwar** [comment] 2021-01-11 23:14
@Bestulo The old extension sometimes has problems loading the types for the recently fetched files, usually a restart of VSCode or closing/opening again solves that problem

**Comment by ije** [comment] 2021-01-11 23:55
seems your deno extension is down.
![image](https://user-images.githubusercontent.com/2883484/104251724-53fa8580-54ab-11eb-8015-495c0257ca51.png)

**Comment by FallingSnow** [comment] 2021-01-14 00:09
If you're using deno lsp, jsx is not supported yet. https://github.com/denoland/deno/issues/8993

If you're not using lsp, I believe it solves many of the import issues.

**Comment by ije** [comment] 2021-01-22 03:54
i am going to close this issue since it is not caused by alephjs.

**Closed by ije** 2021-01-22 03:54 UTC

**Comment by stereosteve** [comment] 2021-01-26 19:56
In the meantime, this will make deno lsp in vscode happy:

```
// @deno-types="https://servestjs.org/@v1.1.7/types/react/index.d.ts"
import React, { useState } from 'react'
```

Taken from [this page](https://servestjs.org/use-jsx)

**Comment by ije** [comment] 2021-01-26 20:18
@stereosteve esm.sh will response a `x-typescript-type` header to provide types check.
