### ISSUE TITLE
The <head/> tag doesn't work in app.tsx when using "srcDir"

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#308] opened 2021-05-10 15:26 UTC
The `head` tag doesn't work in `app.tsx`, the title is not displayed, and the css is not loaded

I tried with ssr disabled, same problem

**app.tsx**

```typescript
import React, { ComponentType } from 'react'

export default function App({ Page, pageProps }: { Page: ComponentType<any>, pageProps: any }) {
  return (
    <main>
      <head>
        <title>hello</title>
        <link rel="stylesheet" href="https://esm.sh/tailwindcss/dist/tailwind.min.css" />
      </head>
      <Page {...pageProps} />
    </main>
  )
}
```

However, when moving it to a page, it works fine:

**pages/index.tsx**

```typescript
import React from 'react'

export default function Home() {
  return (
    <div className="page">
      <head>
        <title>hello</title>
        <link rel="stylesheet" href="https://esm.sh/tailwindcss/dist/tailwind.min.css" />
      </head>
    </div>
  )
}
```

But using this way, the CSS is unloaded then loaded each time I change page

**Comment by jheysondev** [comment] 2021-05-29 02:00
@hazae41 Could you show the error you get when trying to run the program, or does the program run fine and you don't get any errors?

I have reproduced the problem in my local environment but I would like to know if the problem is the same as you have

**Comment by hazae41** [comment] 2021-05-29 12:59
> @hazae41 Could you show the error you get when trying to run the program, or does the program run fine and you don't get any errors?
> 
> I have reproduced the problem in my local environment but I would like to know if the problem is the same as you have

No error, it just fails

**Comment by ije** [comment] 2021-08-24 04:44
i am going to close this since custom `srcDir` option has been removed in beta branch

**Closed by ije** 2021-08-24 04:44 UTC
Labels: ✘ bug
