### ISSUE TITLE
typescript support ?

### ISSUE THREAD

**Issue by elycheikhsmail** [alephjs/aleph.js#318] opened 2021-05-15 00:12 UTC
vscode with default config done by alephjs reconize the import but don't allow type any I don't know what type for returnd value by react function

**Comment by shadowtime2000** [comment] 2021-05-15 06:42
Sorry, but your description of the problem lacks details that could help us understand the situation. Could you clarify along with including stuff like reproduction steps and like a screenshot of the problem?

**Comment by elycheikhsmail** [comment] 2021-05-15 10:10
I create simple hello project with aleph init hello and i run aleph dev then I open hello project in my vscode code I will share with some screenshot and system info deno version etc..

**Comment by elycheikhsmail** [comment] 2021-05-15 12:42
I use ubuntu 20.04 deno v1.9.0 this is link to screenshot https://drive.google.com/file/d/1-TzLfB4CoE3i5aYVvIlGshZoI3dX_1f-/view?usp=sharing

**Comment by ije** [comment] 2021-05-15 15:55
try `deno cache https://esm.sh/react@17.0.2` since the deno vscode extension is not stable

**Comment by elycheikhsmail** [comment] 2021-05-15 21:35
I update alephjs cli from v0.3.0-alpha.32 to v0.3.0-alpha.33 I will see the result and give you  a feedback

**Comment by elycheikhsmail** [comment] 2021-05-16 21:56
after update cli from v0.3.0-alpha.32 to v0.3.0-alpha.33 ,deno- vscode-plunig work correctly, but some time deno lsp fail to run because some time time vscode show this info. I

**Comment by shadowtime2000** [comment] 2021-05-20 23:53
I am going to close this since this isn't a problem on our end, but a problem with the deno vscode extension.

**Closed by shadowtime2000** 2021-05-20 23:53 UTC
