### ISSUE TITLE
Uncaught TypeError cannot set property navigator of #<window> which has only a getter

### ISSUE THREAD

**Issue by AhmetEnesKCC** [alephjs/aleph.js#198] opened 2021-03-16 20:56 UTC
when i tried to > `aleph dev` or `aleph start`

error: Uncaught (in promise) TypeError: Cannot set property navigator of #<Window> which has only a getter
    Object.assign(globalThis, {
           ^
    at Function.assign (<anonymous>)
    at Application.init (https://deno.land/x/aleph@v0.3.0-alpha.8/server/app.ts:410:12)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.8/server/server.ts:177:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.8/cli/dev.ts:21:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.8/cli.ts:147:7)

**Comment by shadowtime2000** [comment] 2021-03-16 20:58
Duplicate of #169.

**Closed by shadowtime2000** 2021-03-16 20:58 UTC
